#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gescom.trace
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GESCOM")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertActeItem(ActeItem instance);
    partial void UpdateActeItem(ActeItem instance);
    partial void DeleteActeItem(ActeItem instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::gescom.trace.Properties.Settings.Default.GESCOMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ActeItem> ActeItems
		{
			get
			{
				return this.GetTable<ActeItem>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ActeItem")]
	public partial class ActeItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private int _Danger;
		
		private int _Question;
		
		private int _Super;
		
		private int _Placer;
		
		private int _Verif;
		
		private int _Cause;
		
		private string _Couleur;
		
		private string _State;
		
		private System.Nullable<int> _Priter;
		
		private System.Nullable<int> _Entrer;
		
		private System.Nullable<double> _Qcder;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnDangerChanging(int value);
    partial void OnDangerChanged();
    partial void OnQuestionChanging(int value);
    partial void OnQuestionChanged();
    partial void OnSuperChanging(int value);
    partial void OnSuperChanged();
    partial void OnPlacerChanging(int value);
    partial void OnPlacerChanged();
    partial void OnVerifChanging(int value);
    partial void OnVerifChanged();
    partial void OnCauseChanging(int value);
    partial void OnCauseChanged();
    partial void OnCouleurChanging(string value);
    partial void OnCouleurChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnPriterChanging(System.Nullable<int> value);
    partial void OnPriterChanged();
    partial void OnEntrerChanging(System.Nullable<int> value);
    partial void OnEntrerChanged();
    partial void OnQcderChanging(System.Nullable<double> value);
    partial void OnQcderChanged();
    #endregion
		
		public ActeItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Danger", DbType="Int NOT NULL")]
		public int Danger
		{
			get
			{
				return this._Danger;
			}
			set
			{
				if ((this._Danger != value))
				{
					this.OnDangerChanging(value);
					this.SendPropertyChanging();
					this._Danger = value;
					this.SendPropertyChanged("Danger");
					this.OnDangerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="Int NOT NULL")]
		public int Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this.OnQuestionChanging(value);
					this.SendPropertyChanging();
					this._Question = value;
					this.SendPropertyChanged("Question");
					this.OnQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Super", DbType="Int NOT NULL")]
		public int Super
		{
			get
			{
				return this._Super;
			}
			set
			{
				if ((this._Super != value))
				{
					this.OnSuperChanging(value);
					this.SendPropertyChanging();
					this._Super = value;
					this.SendPropertyChanged("Super");
					this.OnSuperChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Placer", DbType="Int NOT NULL")]
		public int Placer
		{
			get
			{
				return this._Placer;
			}
			set
			{
				if ((this._Placer != value))
				{
					this.OnPlacerChanging(value);
					this.SendPropertyChanging();
					this._Placer = value;
					this.SendPropertyChanged("Placer");
					this.OnPlacerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Verif", DbType="Int NOT NULL")]
		public int Verif
		{
			get
			{
				return this._Verif;
			}
			set
			{
				if ((this._Verif != value))
				{
					this.OnVerifChanging(value);
					this.SendPropertyChanging();
					this._Verif = value;
					this.SendPropertyChanged("Verif");
					this.OnVerifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cause", DbType="Int NOT NULL")]
		public int Cause
		{
			get
			{
				return this._Cause;
			}
			set
			{
				if ((this._Cause != value))
				{
					this.OnCauseChanging(value);
					this.SendPropertyChanging();
					this._Cause = value;
					this.SendPropertyChanged("Cause");
					this.OnCauseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Couleur", DbType="VarChar(255)")]
		public string Couleur
		{
			get
			{
				return this._Couleur;
			}
			set
			{
				if ((this._Couleur != value))
				{
					this.OnCouleurChanging(value);
					this.SendPropertyChanging();
					this._Couleur = value;
					this.SendPropertyChanged("Couleur");
					this.OnCouleurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(255)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priter", DbType="Int")]
		public System.Nullable<int> Priter
		{
			get
			{
				return this._Priter;
			}
			set
			{
				if ((this._Priter != value))
				{
					this.OnPriterChanging(value);
					this.SendPropertyChanging();
					this._Priter = value;
					this.SendPropertyChanged("Priter");
					this.OnPriterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entrer", DbType="Int")]
		public System.Nullable<int> Entrer
		{
			get
			{
				return this._Entrer;
			}
			set
			{
				if ((this._Entrer != value))
				{
					this.OnEntrerChanging(value);
					this.SendPropertyChanging();
					this._Entrer = value;
					this.SendPropertyChanged("Entrer");
					this.OnEntrerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qcder", DbType="Float")]
		public System.Nullable<double> Qcder
		{
			get
			{
				return this._Qcder;
			}
			set
			{
				if ((this._Qcder != value))
				{
					this.OnQcderChanging(value);
					this.SendPropertyChanging();
					this._Qcder = value;
					this.SendPropertyChanged("Qcder");
					this.OnQcderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
