//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gescom.create.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gescom.create.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap achat {
            get {
                object obj = ResourceManager.GetObject("achat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inventaire {
            get {
                object obj = ResourceManager.GetObject("inventaire", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rupture {
            get {
                object obj = ResourceManager.GetObject("rupture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stagnation {
            get {
                object obj = ResourceManager.GetObject("stagnation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Modifier.
        /// </summary>
        internal static string XtraArticle_Init__Modifier {
            get {
                return ResourceManager.GetString("XtraArticle_Init__Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier l&apos;article en cours..
        /// </summary>
        internal static string XtraArticle_Init_Modifier_l_article_en_cours_ {
            get {
                return ResourceManager.GetString("XtraArticle_Init_Modifier_l_article_en_cours_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Modifier.
        /// </summary>
        internal static string XtraGlobal_Init__Modifier {
            get {
                return ResourceManager.GetString("XtraGlobal_Init__Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier l&apos;entité en cours.
        /// </summary>
        internal static string XtraGlobal_Init_Modifier_l_entité_en_cours {
            get {
                return ResourceManager.GetString("XtraGlobal_Init_Modifier_l_entité_en_cours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOUVEL PLACE.
        /// </summary>
        internal static string XtraGlobal_Init_Nouveau_emplacement {
            get {
                return ResourceManager.GetString("XtraGlobal_Init_Nouveau_emplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOUVELLE CATEGORIE.
        /// </summary>
        internal static string XtraGlobal_Init_Nouvelle_catégorie {
            get {
                return ResourceManager.GetString("XtraGlobal_Init_Nouvelle_catégorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOUVELLE UNITE.
        /// </summary>
        internal static string XtraGlobal_Init_Nouvelle_unité {
            get {
                return ResourceManager.GetString("XtraGlobal_Init_Nouvelle_unité", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATIONS GENERALES.
        /// </summary>
        internal static string XtraPerson_Init_Informations_générales {
            get {
                return ResourceManager.GetString("XtraPerson_Init_Informations_générales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOUVEAU CLIENT.
        /// </summary>
        internal static string XtraPerson_Init_Nouveau_client {
            get {
                return ResourceManager.GetString("XtraPerson_Init_Nouveau_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOUVEAU FOURNISSEUR.
        /// </summary>
        internal static string XtraPerson_Init_Nouveau_fournisseur {
            get {
                return ResourceManager.GetString("XtraPerson_Init_Nouveau_fournisseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOUVEAU PERSONNEL.
        /// </summary>
        internal static string XtraPerson_Init_NOUVEAU_PERSONNEL {
            get {
                return ResourceManager.GetString("XtraPerson_Init_NOUVEAU_PERSONNEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Modifier.
        /// </summary>
        internal static string XtraPerson_Read__Modifier {
            get {
                return ResourceManager.GetString("XtraPerson_Read__Modifier", resourceCulture);
            }
        }
    }
}
